name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version: [1.22.x]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go_version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Test
      run: go test -v ./...
